### ISSUE TITLE
getting a postcss-cli error on ./run

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/www.ubuntu.com#2430]
## Summary

@anthonydillon and me are getting a postcss-cli error on ./run, and so was @barrymcgee [see here](https://www.bountysource.com/issues/49834639-cssnano-is-throwing-an-error-in-the-build)

## Process

do `./run` and you will see it

## Current and expected result

```
➜  www.ubuntu.com git:(master) ./run

yarn run v1.1.0
warning package.json: License should be a valid SPDX license expression
$ node-sass --include-path node_modules static/sass --output static/css && postcss --use autoprefixer --replace static/css/**/*.css && postcss --use cssnano --dir static/css/minified static/css/**/*.css
Rendering Complete, saving .css file...
Wrote CSS to /Users/peter/Branches/www.ubuntu.com/static/css/styles.css
Wrote 1 CSS files to /Users/peter/Branches/www.ubuntu.com/static/css
✔ Finished static/css/styles.css (834 ms)
⠋ Processing static/css/styles.cssTypeError: error.setMessage is not a function
    at LazyResult.handleError (/Users/peter/Branches/www.ubuntu.com/node_modules/postcss-cli/node_modules/postcss/lib/lazy-result.js:158:23)
    at /Users/peter/Branches/www.ubuntu.com/node_modules/postcss-cli/node_modules/postcss/lib/lazy-result.js:192:27
✖ Processing static/css/styles.css


✖ Syntax Error: static/css/styles.css

 [Colon is expected
(node:35) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: err.showSourceCode is not a function
Done in 21.61s.
```

basically, seems like there is a syntax error somewhere, but might be the postcss-cli itself

**Comment by anthonydillon** [comment]
This was an encoding issue in SVG background. This has been fixed and the issue is no longer present.
